name: Keep Supabase Awake

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes (cron format)
  workflow_dispatch:        # Allows manual triggering via GitHub UI

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          curl -sS -X GET "$SUPABASE_URL/rest/v1/ping_table?select=id&limit=1" \
            -H "apikey: $SUPABASE_ANON_KEY" \
            -H "Authorization: Bearer $SUPABASE_ANON_KEY"